// src/components/Experience.vue
<template>
  <section id="experience" class="experience flex-center-col">
    <projects></projects>
    <tools 
      :set-active="this.setActive" 
      :clear-active="this.clearActive"
    ></tools>
  </section>
</template>

<script>
import Projects from './Projects'
import Tools from './Tools'

export default {
  name: 'experience',
  components: {
    Projects, Tools
  },

  data () {
    return {
      activeTool: null
    }
  },

  methods: {
    setActive (tool) {
      this.activeTool = tool
    },

    clearActive () {
      this.activeTool = null
    }
  }
}
</script>

<style scoped lang="sass">
.experience
  padding: 0
</style>

// src/Experience.jsx
import React from 'react';
import Tools from './Tools';
import Projects from './Projects';
import './Experience.css';

class Experience extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "activeTool": "",
        }

        this.setActive = this.setActive.bind(this);
        this.clearActive = this.clearActive.bind(this);
    }
    setActive(tool) {
        this.setState({"activeTool": tool});
    }
    clearActive() {
        this.setState({"activeTool": ""});
    }
    render() {
        return (
            <section id="experience" className="experience flex-center-col">
                <Tools 
                    setActive={this.setActive} 
                    clearActive={this.clearActive} 
                />
                <Projects activeTool={this.state.activeTool} />
            </section>
        );
    }
}

export default Experience;
