// src/components/Projects.vue
<template>
<div class="projects">
  <h2 class="text-center">My Projects</h2>
  <div class="projects__featured">
    <div
      v-for="project in featured"
      class="card"
    >
      <img 
        class="project__thumbnail"
        :src="project.thumbnail"
        width="384"
        height="225"
        :alt="project.name"
        target="_blank"
      />
      <div class="card__text">
        <h2>{{project.name}}</h2>
        <p>{{project.description}}</p>
      </div>
    </div>
    <button @click="showGrid">More Projects</button>
    <div role="grid">
      <a
        v-for="project in projects"
        role="gridcell"
        :href="project.link"
        target="_blank"
        class="project"
        :class="{'is-active': isActive(project)}"
        @click="trackClick(project.name)"
      >
        <img 
          class="project__thumbnail"
          :src="project.thumbnail"
          width="384"
          height="225"
          :alt="project.name"
          target="_blank"
        />
        <div class="project__name">{{project.name}}</div>
        <div class="project__shade"></div>
      </a>
  </div>
</div>
</template>

<script>
// import _ from 'lodash'
import projects from '../project-data'
// import { mixpanel } from '../main'

export default {
  name: '',
  components: {
  },

  data () {
    return {
      projects
    }
  },

  methods: {
  }
}
</script>

<style scoped lang="sass">
</style>

// src/Projects.jsx
import React from 'react';
import projects from './projects-data.js';
import './Projects.css'

const getThumbnail = project => {
    const getCodepenUrl = id => `https://codepen.io/oknoblich/pen/${id}/image/small.png`;
    return project.codepenId ? getCodepenUrl(project.codepenId) : project.thumbnail;
}

const renderThumbnail = (project, i) => {
    if (getThumbnail(project)) {
        return <img className="project__thumbnail" src={getThumbnail(project)} width="384" height="225" alt={project.name} target="_blank" />;
    } else {
        return (<div className="project__placeholder"><span>Project Thumbnail {i + 1}</span></div>);
    }
};

const getActiveClass = (project, activeTool) => {
    return project.tools.indexOf(activeTool) > -1 ? 'is-active' : 'is-inactive';
}

const getLink = project => {
    const codepenBase = 'http://codepen.io/mCornish/full/';
    return project.codepenId ? codepenBase + project.codepenId : project.link;
}


export default function Projects({activeTool}) {
    return (
        <div className="projects">
            <h2 className="text-center">My Projects</h2>
            <div role="grid">
                {projects.map((project, i) => (
                    <a role="gridcell" href={getLink(project)} target="_blank" key={project.id} className={`project ${getActiveClass(project, activeTool)}`}>
                        {renderThumbnail(project, i)}
                        <div className="project__name">{project.name}</div>
                        <div className="project__shade"></div>
                    </a>
                ))}
            </div>
        </div>
    );
}
